# Generated by Django 4.1.3 on 2022-11-12 12:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.driver')),
            ],
        ),
    ]
